### ISSUE TITLE
Question - is it possible to specify a data pattern?

### ISSUE THREAD

**Issue by charris-msft** [DamascenoRafael/mqtt-simulator#1]
I love what you've built, but I have a scenario where for a demo I need to simulate a freezer with a problem.

This pattern needs to look something like this, where the data repeats every n samples:

![image](https://user-images.githubusercontent.com/74415662/226980007-e9029348-c9bb-40b5-a08a-6d95b957383a.png)

Have you thought about this kind of scenario? Is it possible within the current implementation?

Thanks!

**Comment by Maasouza** [comment]
Unfortunately, the current implementation does not support failures simulation.

At first, we implemented this to simulate human body information, like oximetry and temperature and then made it more generic, so this kind of scenario was out of our scope. However, it would be great to cover your scenario too. 

As an input, are you expecting to give a list previously created with the data sequence, or just the limits and receive randomly generated data each cycle?

**Comment by charris-msft** [comment]
I've been considering a couple options:
- specifying a list of values that the simulator would loop through
- making the pattern a bit less random where values can only increase until the max is reached, then it would start over again (sawtooth pattern)

For now, I'm going to proceed with using it as-built, but if I so make some modifications I'll be sure to submit a PR so you can review them.

**Comment by DamascenoRafael** [comment]
Hi @charris-msft.
@Maasouza and I made some changes to the simulator that might help you.

We add the following parameters to the _date_ object:
`initial_value`, `reset_probability`, `increase_probability` and `restart_on_boundaries`.

Besides that, we've also added a new `math_expression` `type` to the _data_ object.

Please take a look at the updated _README_ file to see if these changes might suit your use case.

The only breaking change is that now the `RETAIN_PROBABILITY` parameter is part of the _data_ object and not the _topic_ one.

Let us know if there are any other improvements that may allow the simulator to be used in more cases.
